from fastapi import APIRouter

from shylock_trial.adapter.inbound.api.v1.evidence_search_router import evidence_search_router
from shylock_trial.adapter.inbound.api.v1.present_evidence_router import present_evidence_router
from shylock_trial.adapter.inbound.api.v1.trial_progression_router import trial_progression_router
from shylock_trial.adapter.inbound.api.v1.tubal_skill_router import tubal_skill_router

shylock_trial_router = APIRouter(prefix="/shylock-trial")
shylock_trial_router.include_router(trial_progression_router)
shylock_trial_router.include_router(evidence_search_router)
shylock_trial_router.include_router(tubal_skill_router)
shylock_trial_router.include_router(present_evidence_router)
