"""Tunable combat / trial balance constants."""

SHYLOCK_DP_START = 50
DP_MAX = 100

DP_FOUGHT_TO_END_THRESHOLD = 80
DP_DIGNITY_ENDING_THRESHOLD = 60
DP_SURVIVAL_ENDING_THRESHOLD = 40
DP_JESSICA_EPILOGUE_THRESHOLD = 90

SKILL_TUBAL_COST = 30
SKILL_CROWD_COST = 40

LAUNCELOT_SKILL_DP_GAIN = 10

VENICE_CONTRADICTION_SKILL_COST = 40
