"""Tunable combat / trial balance constants."""

SHYLOCK_HP_MAX = 60
SHYLOCK_DP_START = 50
DP_MAX = 100
DP_GOOD_ENDING_THRESHOLD = 70

SKILL_TUBAL_COST = 30
SKILL_CROWD_COST = 40

LAUNCELOT_SKILL_COST = 20
LAUNCELOT_SHYLOCK_HP_HEAL = 15

VENICE_CONTRADICTION_SKILL_COST = 40
VENICE_CONTRADICTION_HP_HEAL = 20
