"""Tunable combat / trial balance constants."""

SHYLOCK_HP_MAX = 60
SHYLOCK_DP_START = 50
PORTIA_HP_MAX = 100
DP_MAX = 100
DP_GOOD_ENDING_THRESHOLD = 70

SKILL_OBJECTION_COST = 20
SKILL_TUBAL_COST = 30
SKILL_CROWD_COST = 40
